apiVersion: v1
kind: ReplicationController
metadata:
  name: orchestrator
spec:
  replicas: 1
  selector:
    app: orchestrator
  template:
    metadata:
      name: orchestrator
      labels:
        app: orchestrator
    spec:
      containers:
      - name: orchestrator
        image: 192.168.2.105:5000/netperf
        imagePullPolicy: IfNotPresent
        args:
        - --mode=orchestrator
        #- -debug
        ports:
        - name: service-port
          protocol: TCP
          containerPort: 5202